### ISSUE TITLE
AttributeError: 'ParsedRequirement' object has no attribute 'req'

### ISSUE THREAD

**Issue by mayifangyuan** [GNSSpy-Project/gnsspy#7]
when I input "sudo python setup.py install", and the output is as following.
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    install_requires=load_requirements("requirements.txt"),
  File "setup.py", line 16, in load_requirements
    return [str(ir.req) for ir in reqs]
AttributeError: 'ParsedRequirement' object has no attribute 'req'

my python version is 2.7.10, and numpy, patools, pandas and matplotlib have been installed.

**Comment by geomsi** [comment]
Hi,

`gnsspy` works only in Python 3, and currently below 3.8 versions.

**Comment by LLLavinia** [comment]
this issue also happens to python3.7

**Comment by nahimilega** [comment]
Replace the return statement of ```load_requirements(fname):``` function in setup.py with this ```return [str(ir.requirement) for ir in reqs] ```.
It should look like:
```
def load_requirements(fname): 
    reqs = parse_requirements(fname, session="test")
    return [str(ir.requirement) for ir in reqs]
```

**Comment by uhFan** [comment]
Did you solve this problem?

**Comment by uhFan** [comment]
Did you solve that problem?  I have the same problem.
My python version is 3.9/3.8 and numpy, patools, pandas and matplotlib have been installed.

**Comment by WhitCrow** [comment]
> 
> 
> Replace the return statement of `load_requirements(fname):` function in setup.py with this `return [str(ir.requirement) for ir in reqs] `.
> It should look like:
> 
> ```
> def load_requirements(fname): 
>     reqs = parse_requirements(fname, session="test")
>     return [str(ir.requirement) for ir in reqs]
> ```
its worked , would you "pull reques" it
