### ISSUE TITLE
Fatal

### ISSUE THREAD

**Issue by kedoneyes** [GNSSpy-Project/gnsspy#9]
When I execute the command python setup.py install , there is an error。
Traceback (most recent call last):                                                                                      
       File "setup.py", line 31, in <module>                 
                 install_requires=load_requirements("requirements.txt"),                                             
       File "setup.py", line 17, in load_requirements                                                                    
               return [str(ir.req) for ir in reqs]                                                      
      File "setup.py", line 17, in <listcomp>                                                                 
                  return [str(ir.req) for ir in reqs]                                                                  
AttributeError: 'ParsedRequirement' object has no attribute 'req'

**Comment by uhFan** [comment]
Did you solve that problem? I have the same problem.
My python version is 3.9/3.8 and numpy, patools, pandas and matplotlib have been installed.
